In [15]:
import time
import numpy as np

# Función para encontrar una celda vacía
def find_empty_location(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return (i, j)  # Retorna fila, columna
    return None

# Función para verificar si un número es seguro de colocar
def is_safe(board, row, col, num):
    # Verificar la fila
    if num in board[row]:
        return False
    # Verificar la columna
    if num in [board[i][col] for i in range(9)]:
        return False
    # Verificar subcuadro 3x3
    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(start_row, start_row + 3):
        for j in range(start_col, start_col + 3):
            if board[i][j] == num:
                return False
    return True

# Heurística MRV: Encontrar la celda vacía con el menor número de posibilidades
def find_best_cell(board):
    best_options = None
    best_cell = None
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                options = [num for num in range(1, 10) if is_safe(board, i, j, num)]
                if best_options is None or len(options) < len(best_options):
                    best_options = options
                    best_cell = (i, j)
    return best_cell, best_options

# Función que resuelve el Sudoku usando Backtracking con MRV heurística
def solve_sudoku(board):
    # Encontrar la mejor celda vacía utilizando MRV
    best_cell, options = find_best_cell(board)

    if best_cell is None:  # Si no hay celdas vacías, el tablero está resuelto
        return True

    row, col = best_cell

    for num in options:
        if is_safe(board, row, col, num):
            board[row][col] = num  # Intentar colocar el número

            if solve_sudoku(board):  # Continuar con el siguiente paso
                return True

            board[row][col] = 0  # Si no funciona, deshacer el cambio (backtrack)

    return False  # Si no se puede resolver, regresar False

# Tablero inicial del Sudoku (0 representa una celda vacía)
board = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
]

# Crear una copia del tablero inicial
initial_board = np.array(board)

# Medir el tiempo de ejecución
start_time = time.time()

# Resolver el Sudoku
if solve_sudoku(board):
    print("¡Sudoku resuelto correctamente!")
else:
    print("No se pudo resolver el Sudoku.")

# Calcular el tiempo de convergencia
end_time = time.time()
elapsed_time = end_time - start_time

# Mostrar el tablero resuelto
print(np.array(board))

# Mostrar el tiempo que tardó en converger
print(f"Tiempo de convergencia: {elapsed_time:.4f} segundos")


¡Sudoku resuelto correctamente!
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Tiempo de convergencia: 0.0235 segundos
